trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: deploymentDefaultLocation
    value: japaneast

jobs:
- job:
  steps: 
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: deploy/main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deployDemoManualsStorageAccount $(DeployDemoManualsStorageAccount)
  